services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=cozinha'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=myuser'
    ports:
      - '13306:3306'